Search_Work/Arrea/Employer/Models/PageAboutCompanyViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Search_Work.Arrea.Employer.Models
{
  public class PageAboutCompanyViewModel
  {
    public Guid CompanyId { get; set; }
    public string NameConpany { get; set; }

    public Guid EmployeeId { get; set; }
    public string Address { get; set; }
    public string Requisites { get; set; }

    public string Phone { get; set; }
    public string Email { get; set; }


    public string CompanyLogo { get; set; }
    public string Fasebook { get; set; }
    public string Linkedin { get; set; }
    public string Site { get; set; }

    public string Description { get; set; }
    public string City { get; set; }
    public string Street { get; set; }

    public List<string> Certificates { get; set; }

    public string Status { get; set; }

    
  }
}

Search_Work/Arrea/Employer/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Search_Work.Arrea.Employer.Models;
using Search_Work.Data;
using Search_Work.Models.ArreaDatabase.Resumes;
using Search_Work.Models.Pagination;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Search_Work.Arrea.Employer.Controllers
{
  public class CompanyController : Controller
  {
    private oxana1404 dbContext;

    public CompanyController(oxana1404 dbContext)
    {
      this.dbContext = dbContext;
    }


    public ActionResult ProfileCompany()
    {
      var usName = HttpContext.User.Identity.Name;
      //var repo = new EmployerRepository(this.dbContext);
      //var employer = repo.GetByAccountUserName(usName);
      //var companyId 


      var company = dbContext.Companies
        .Include(e => e.Employers).ThenInclude(e => e.AccountUser)
        .Include(c => c.City)
        .FirstOrDefault(x => x.Employers.FirstOrDefault(i => i.AccountUser.Email == usName) != null);

      var emp = dbContext.Employers.Include(e => e.Company)
        .Include(e => e.AccountUser).FirstOrDefault(e => e.AccountUser.UserName == usName);

      var city = company.City == null ? "Немає" : company.City.Name;
      var address = company.Adress == null ? "Немає" : company.Adress;
      var fullAdress = $"{city}, {company.Adress}";

      var model = new PageAboutCompanyViewModel()
      {
        CompanyId = company.Id,
        EmployeeId = emp.Id,
        NameConpany = company.Name,
        Address = fullAdress,
        // Street = company.
        // toDo Recvisite
        // Requisites = company
        Phone = company.PhoneNumber,
        Email = company.Email,
        Fasebook = company.Facebook,
        CompanyLogo = company.CompanyLogoUrl,
        Description = company.Description,

        Site = company.Site,
        // toDo Certificates
        //Certificates = 
        Status = company.Status == false ? "Не активно" : "Активно"

      };

      return View("/Arrea/Employer/Views/Company/PageAboutCompany.cshtml", model);
    }

    // Сохраненные резюме
    public ActionResult SavedResume(int currentPage = 1)
    {

      var user = HttpContext.User.Identity.Name;

      var employer = dbContext.Employers.Include(i => i.AccountUser)
                .Include(e => e.Vacancies)
                .FirstOrDefault(x => x.AccountUser.Email == user);
      var cand = dbContext.Candidates.Include(i => i.AccountUser)
        .FirstOrDefault(c => c.AccountUser.UserName == user);


      var allresume = dbContext.Resumes
        .Include(resum => resum.SavedResumes).ThenInclude(r => r.Resume)
        .Include(resum => resum.SavedResumes).ThenInclude(r => r.Employer)
                .Include(i => i.Candidate).ThenInclude(c => c.City)
                .Where(i => i.SavedResumes
                .FirstOrDefault(x => x.Employer.Id == employer.Id) != null);
      //repoRes.GetByEmployerIdWhitSaveResume(employer.Id);

 

      var count = allresume.Count();

      const int skipCount = 4;
      Decimal decResumeCount = allresume.Count();
      Decimal decCountPages = Math.Ceiling(decResumeCount / skipCount);

      int countPages = Decimal.ToInt32(decCountPages);

      int resumeCount = Decimal.ToInt32(decResumeCount);

      if (currentPage > countPages)
      {
        currentPage = 1;
      }
      var savResum = dbContext.SavedResumes.Where(sr => sr.EmployerId == employer.Id).ToList();

      var resumesSaved = new List<ResumeViewModel>();


      resumesSaved.AddRange(allresume.Skip(skipCount * currentPage - skipCount)
              .Take(skipCount).ToList()
              .Select(res => new ResumeViewModel()
              {

                // toDo isCheced
                //IsCheced = 
                // toDo ActionWhithFavorite
                //ActionWhithFavorite = 
                Id = res.Id,
                NameResume = res.Candidate?.Name,
                Salary = res.Salary,
                Birthday = res.Candidate.Birthday,
                Cities = new List<CityNameViewModel>() { new CityNameViewModel()
                {
                    CityName = res.Candidate?.City?.Name
                }},

                Date = res.SavedResumes.FirstOrDefault(r => r.ResumeId == res.Id).DateSaved,
                SavedResumeId = res.SavedResumes.FirstOrDefault(r => r.ResumeId == res.Id).Id,

                FotoUrl = res.Candidate?.Avatar,

                LinkPageResum = Url.Action("AboutResume", "Resume", new { resumeId = res.Id })
                //ToDo LinkFavorites Resume
                //ChekedFavorites = 

              }));




      var model = new Page2ResumeViewModel()
      {

        EmployerId = employer.Id,
        Resumes = resumesSaved,
        Pagination = new CataloguePaginationViewModel()
        {
          CurrentPage = currentPage,
          DisplayOnPage = skipCount,
          TotalCount = countPages,
          ActionName = "SavedResume",
          ControllerName = "Company",
          ObjectParameter = new Dictionary<string, string> {
                    {
                        "employerId", employer.Id.ToString()
                    }}
        }
      };
      return View("/Arrea/Employer/Views/Company/SavedResumeVacancy.cshtml", model);
    }

    [HttpGet]
    public ActionResult DeleteSaveResume(Guid saveResumeId)
    {

      var savResum = dbContext.SavedResumes.FirstOrDefault(sr => sr.Id == saveResumeId);
     
      if (savResum == null)
      {
        return NotFound();
      }
      dbContext.SavedResumes.Remove(savResum);
      // dbContext.SaveChanges();

      return RedirectToAction(nameof(SavedResume));
    }

    [HttpPost]
    public ActionResult DeleteSaveResumeSubmit()
    {
      return RedirectToAction(nameof(SavedResume));
    }
  }
}

Search_Work/Arrea/Employer/Controllers/VacancyController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Search_Work.Arrea.Candidate.Models;
using Search_Work.Arrea.Employer.Models;
using Search_Work.Data;
using Search_Work.Models.ArreaDatabase.Vacancies;
using Search_Work.Models.DefaultData;
using Search_Work.Models.Helper;
using Search_Work.Models.ViewModel;
using Search_Work.Models.ViewModel.Home.Resumes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static Search_Work.Arrea.Employer.Models.CreateVacancyViewModel;

namespace Search_Work.Arrea.Employer.Controllers
{
    public class VacancyController : Controller
    {
        private readonly oxana1404 dbContext;

        public VacancyController(oxana1404 context)
        {
            this.dbContext = context;

        }

        // VACANCIES_Employer  ----------------------------------------------------------
        public ActionResult EmploeeVacancies(string filterType = null, string nameVacancy = null)
        {

            var usName = HttpContext.User.Identity.Name;


            List<Vacancy> allVacanciesCandidate = null;
            if (nameVacancy != null)
            {
                allVacanciesCandidate = dbContext.Vacancies.Include(vac => vac.PageViews).ThenInclude(res => res.Vacancy)
                            .Include(resum => resum.Responses).ThenInclude(res => res.Vacancy)
                  .Include(v => v.Employer).ThenInclude(v => v.AccountUser)
                  .Where(v => v.Employer.AccountUser.Email == usName && v.Name == nameVacancy).ToList();

                //.Include(vac => vac.PageViews).Include(vac => vac.Responses).Include(v => v.Employer.AccountUser).Where(x => x.Employer.AccountUser.Email == userName);
            }
            else
            {
                allVacanciesCandidate = dbContext.Vacancies.Include(v => v.City)
                            .Include(vac => vac.PageViews).ThenInclude(res => res.Vacancy)
                            .Include(resum => resum.Responses).ThenInclude(res => res.Vacancy)
                  .Include(v => v.Employer)
                  .ThenInclude(res => res.AccountUser)
                  .Where(v => v.Employer.AccountUser.Email == usName).ToList();
            }


            var count = allVacanciesCandidate.Count();

            // ToDo переделать e.AccountUser.Email на e.AccountUser.FirstName
            var employer = dbContext.Employers.Include(e => e.AccountUser)
                                                .Include(e => e.Company).Include(e => e.Vacancies)
                                        .FirstOrDefault(e => e.AccountUser.Email == usName);


            IEnumerable<Vacancy> vacansiesByFilter = null;

            var vacanciesEmployer = new List<EmployerVacancieViewdel>();

            if (filterType != null)
            {
                switch (filterType)
                {
                    case TypesSortVacancy.DataId:
                        vacansiesByFilter = allVacanciesCandidate.OrderBy(r => r.DateCreate).ToList();
                        break;
                    case TypesSortVacancy.ResponseId:
                        vacansiesByFilter = allVacanciesCandidate.OrderByDescending(r => r.Responses.Count);
                        break;
                    case TypesSortVacancy.NameId:
                        vacansiesByFilter = allVacanciesCandidate.OrderBy(r => r.Name).ToList();
                        break;
                        //ToDo Sort Region - ?????
                        //case TypesSortVacancy.RegionId:
                        //    vacansiesByFilter = allVacanciesCandidate.OrderBy(r => r.Employer.AccountUser.);
                        //    break;
                }

            }
            else
            {
                vacansiesByFilter = allVacanciesCandidate;
            }

            vacanciesEmployer.AddRange(vacansiesByFilter.Select(vac => new EmployerVacancieViewdel()
            {
                VacancyId = vac.Id,

                DateCreate = vac.DateCreate,

                NameVacancies = vac.Name,
                Salary = vac.Wage,
                City = vac.City?.Name,
                DatePublication = vac.DatePublication.ToString("dd/MM/yyyy"),
                Status = vac.Status,
                //// toDo Editor
                //Editor = "Павлов Олександр",

                CountLinkFeeback = vac.Responses.Count(),

                CountLinkNewFeeback = vac.Responses.Count(),

                CountLinkViews = vac.PageViews.Count,// repoResume.GetByVacancyIdWhitViewPage(vac.Id).Count(),//vac.ViewsResume.Count,
                                                     // toDo CountCandidate


            }));


            //
            var model = new PageEmployeeVacanciesViewModel()
            {
                EmployeeVacancies = vacanciesEmployer,
                CompanyId = employer.CompanyId.Value,

                TypeSortFilter = filterType
            };
            return View("/Arrea/Employer/Views/Employee/EmployeeVacancies.cshtml", model);
        }

        public ActionResult Create()
        {


            var cities = dbContext.Cities.Select(city => new CityViewModel()
            {
                CityName = city.Name,
                Id = city.Id
            }).ToList();

            var fieldsActivity = dbContext.FieldActivities.Select(field => new FieldActivityViewModel()
            {
                Name = field.Name,
                Id = field.Id
            }).ToList();


            var employments = dbContext.Employments.Include(v => v.Vacancies).Select(field => new EmploymentViewModel()
            {
                Id = field.Id,
                NameField = field.Name
            }).ToList();


            var listExpOfWork = dbContext.ExperienceOfWorks.Include(v => v.Vacancies).Select(field => new ExperienceOfWorkViewModel()
            {
                Id = field.Id,
                NameField = field.NameField
            }).ToList();

            var model = new CreateVacancyViewModel()
            {
                Cities = cities,
                Fields = fieldsActivity,
                Employments = employments,
                ExperienceOfWorks = listExpOfWork,

                // EmployerId = employer.Id
            };

            return View("/Arrea/Employer/Views/Vacancy/CreateVacancy.cshtml", model);
        }

        [HttpPost]
        public ActionResult Create(CreateVacancyViewModel model)
        {



            // Employer IDENTITY
            var userName = this.HttpContext.User.Identity.Name;

            var employer = dbContext.Employers.Include(e => e.AccountUser)
              .Include(e => e.Contact)
                                  .Include(e => e.Company)
                                  .Include(e => e.Vacancies).FirstOrDefault(x => x.AccountUser.UserName == userName);


            // ---------------- Company data ----------------------

            //var company = repoComp.GetAll().Include(c => c.Employers).ThenInclude(c => c.Vacancies)
            //                               .ThenInclude(c => c.Employer)
            //                                .FirstOrDefault(comp => comp.Id == employer.CompanyId);


            var city = dbContext.Cities.Include(i => i.Vacancies)
                      .Include(i => i.Companies)
                      .Include(i => i.Candidates).FirstOrDefault(c => c.Id == model.CityId);

            var fieldActivity = dbContext.FieldActivities.Include(f => f.Vacancies)
                                   .Include(f => f.Resumes).FirstOrDefault(x => x.Id == model.FieldActivityId);


            var employment = dbContext.Employments.Include(e => e.Vacancies)
                                             .FirstOrDefault(e => e.Vacancies.Select(i => i.Id == model.EmploymentId) != null);

            var expOfWork = dbContext.ExperienceOfWorks.Include(e => e.Vacancies).FirstOrDefault(ex => ex.Id == model.ExperienceOfWorkId);

            var newVacancy = new Vacancy();

            newVacancy.Id = Guid.NewGuid();
            newVacancy.Name = model.Name;

            newVacancy.Wage = model.Salary;
            newVacancy.DateCreate = DateTime.Now;

            // toDo DataPublication

            if (fieldActivity != null)
                newVacancy.FieldActivity = fieldActivity;

            if (employer != null)
                newVacancy.Employer = employer;

            if (city != null)
                newVacancy.City = city;
            if (employment != null)
                newVacancy.TypeEmployment = employment;
            if (expOfWork != null)
                newVacancy.ExperienceOfWork = expOfWork;

            newVacancy.Description = model.Description;
            newVacancy.Requirement = model.Requirement;
            newVacancy.Responsibilities = model.Responsibilitie;
            newVacancy.ForeignLanguages = model.ForeignLanguages;


            if (model.UseCompanyContact == false && model.UsePersonalContact == false)
            {
                newVacancy.EmailPerson = model.EmailContactPerson;
                newVacancy.PhoneNumberPerson = model.PhoneNumberContactPerson;
                newVacancy.ContactNamePerson = model.ContactPerson;
            }
            else if (model.UsePersonalContact == true)
            {
                newVacancy.ContactNamePerson = employer.Contact.Email;
                newVacancy.PhoneNumberPerson = employer.Contact.Phone;
                newVacancy.EmailPerson = employer.Contact.Email;

                newVacancy.IsUsePersonalContact = model.UsePersonalContact;
            }
            else if (model.UseCompanyContact == true)
            {

                newVacancy.ContactNamePerson = employer.Company.Email;
                newVacancy.PhoneNumberPerson = employer.Company.PhoneNumber;
                newVacancy.EmailPerson = employer.Company.Email;

Search_Work/Arrea/Employer/Views/Company/DeleteSaveResume.cshtml
@{
  Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="topMenuNavigation">
    @*<div class="cont">
            <a id="zcilkaTopMenuNavigation" href="@Url.Action("ProfileCompany", "Company")"><b> Профіль компанії</b></a>
            <a id="zcilkaTopMenuNavigation" href="@Url.Action("EmployeersCompany", "Employee")"><b> Працівники </b></a>


        </div>*@
</div>

<hr id="lineMenu" />

<div class="row" id="container">
    <h3><b>Резюме -  </b></h3>
    <h4><b>Видалити резюме з збережених </b></h4>
</div>

<hr>
<div class="row" id="container">
    <form method="post" asp-action="DeleteSaveResumeSubmit" asp-controller="Company" name="myForm" >

    </form>
</div>

<style>
    #lineMenu {
        display: block;
        height: 1px;
        border: 0;
        border-top: 2px solid #073b40e6;
        margin: 1em 0;
        padding: 2px;
    }

    .topMenuNavigation {
        margin-left: 150px;
        padding: 5px;
    }

  


    #zcilkaTopMenuNavigation {
        padding-top: 10px;
        padding-bottom: 10px;
        display: block;
        color: darkblue;
        padding-left: 100px;
        font-size: 20px;
    }
</style>

Search_Work/Arrea/Employer/Views/Company/PageAboutCompany.cshtml
@model Search_Work.Arrea.Employer.Models.PageAboutCompanyViewModel

@{
  Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="topMenuNavigation">
    <div class="cont">
        <a id="zcilkaTopMenuNavigation" href="@Url.Action("ProfileCompany", "Company")"><b> Профіль компанії  </b></a>
        <a id="zcilkaTopMenuNavigation" href="@Url.Action("EmployeeCompany", "Employee", new { companyId  = Model.CompanyId})"><b> Працівники </b></a>
         @*<a id="zcilkaTopMenuNavigation" href="@Url.Action( "ProfileCompany", "Company", new{   })">Компанія</a>*@
         <a id="zcilkaTopMenuNavigation" href="@Url.Action( "EmploeeVacancies", "Vacancy", new{  })">Вакансії</a>
        <a id="zcilkaTopMenuNavigation" href="@Url.Action( "SavedResume", "Company", new{   })">Збережені резюме</a>

    </div>
</div>

<hr id="lineMenu" />

<div class="row" id="container">
    <h3>Профіль компанії</h3> - <h3 style="color: darkblue; "><b>@Model.NameConpany</b></h3>
</div>

<hr>
<div class="row" id="container">
    <div class="c" style="float: left; width: 49%"> 
        <h3 style="color: blue; "><b>@Model.Status</b></h3>
        <hr />
        <h3><b>Компанія:</b> @Model.NameConpany</h3>
        <h3><b>Facebook:</b>  @Model.Fasebook</h3>
        <h3><b>Sate:</b>  @Model.Site</h3>
        

        </div>
    <div class="c" style="float: left; width: 49%">

        <div class="commonText">
            @if (Model.CompanyLogo == null)
            {
            <img id="logo" src="~/images/LogoCompany.png" title="@Model.NameConpany" />
            }
            else
            {
            <img id="logo" src="@Model.CompanyLogo" title="@Model.NameConpany" />

            }

        </div>
    </div>

</div>
<hr>
<div class="row" id="container">
    <h3> <b>Tel.:</b> @Model.Phone</h3>
    <h3><b>Email:</b>  @Model.Email</h3>


</div>
    <hr>
    <div class="row" id="container">
        <div class="c" style="float: left; width: 49%">

            <h3>Адреса:</h3>
            <hr />
            <h3>  @Model.Address</h3>
            @*<h3>Sate:  @Model.Site</h3>*@


        </div>
        <div class="c" style="float: left; width: 49%">

            <div class="commonText">

                <h4><b>Опис та історія компанії :</b></h4>
                <hr />
                <h4>@Model.Description</h4>

            </div>
        </div>

    </div>
    <div class="row" id="container">

        <h3><b><a href="@Url.Action("Edit", "Companies", new { id = Model.CompanyId, empId = Model.EmployeeId })">Змінити</a></b></h3>
    </div>

    <style>
        #lineMenu {
            display: block;
            height: 1px;
            border: 0;
            border-top: 2px solid #073b40e6;
            margin: 1em 0;
            padding: 2px;
        }

        .topMenuNavigation {
            margin-left: 50px;
            padding: 5px;
        }


        .cont {
            display: flex;
            flex-direction: row;
        }

        #zcilkaTopMenuNavigation {
            padding-top: 10px;
            padding-bottom: 10px;
            display: block;
            color: darkblue;
            padding-left: 70px;
            font-size: 20px;
        }

        img {
            width: 25%;
        }

        &:hover {
            background-color: rgba(115,220, 224, 1);
        }
    </style>

Search_Work/Arrea/Employer/Views/Company/SavedResumeVacancy.cshtml
@model Search_Work.Arrea.Employer.Models.Page2ResumeViewModel

@{
      Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="topMenuNavigation">
    <div class="cont">
        <a id="zcilkaTopMenuNavigation" href="@Url.Action("SavedResume", "Company")"><b> Збережені резюме</b></a>
        @*<a id="zcilkaTopMenuNavigation" href="@Url.Action("", "Company")"><b> Шаблони пошуку резюме </b></a>*@

        @*<a id="zcilkaTopMenuNavigation" href="@Url.Action("EmployeeCompany", "Employee", new { companyId  = Model.CompanyId})"><b> Працівники </b></a>*@
        @*<a id="zcilkaTopMenuNavigation" href="@Url.Action( "ProfileCompany", "Company", new{   })">Компанія</a>*@
        <a id="zcilkaTopMenuNavigation" href="@Url.Action( "EmploeeVacancies", "Vacancy", new{  })">Вакансії</a>
        @*<a id="zcilkaTopMenuNavigation" href="@Url.Action( "SavedResume", "Company", new{   })">Збережені резюме</a>*@


    </div>
</div>

<hr id="lineMenu" />

<div class="row" id="container">
    <h3><b>Збережені резюме</b></h3>
</div>

<hr />
<div class="row" id="container">


    @foreach (var resume in Model.Resumes)
    {

    <span style="float: left; width: 49%">
        <a href="@Url.Action("AboutResume", "ResumeHome", new { resumeId = resume.Id })">
            <span>@resume.NameResume - </span>
        </a>
        <span> @resume.Salary  грн/міс</span>

        @foreach (var city in resume.Cities)
        {
        <span>@city.CityName, </span>
        }

    </span>
    <div style="float: left; width: 49%">
        <div>
            (@resume.Date.ToString("dd/MM/yyyy"))
            <hr />
        </div>

        @if (resume.FotoUrl == null)
        {
        <img id="logo" src="~/images/person.png" title="@resume.NameResume" />
        }
        else
        {
        <img id="logo" src="@resume.FotoUrl" title="@resume.NameResume" />

        }

    </div>



        <div>

        </div>

        <h5><a href="@Url.Action("DeleteSaveResume","Company", new { saveResumeId = resume.SavedResumeId })"><b> Удалить </b></a></h5>

        <hr />
        <br>

    }



</div>
<hr />
<div id="container">
    @Html.Partial("~/Views/Shared/Elements/CataloguePagination/_cataloguePagination.cshtml", Model.Pagination)
</div>

<style>
    #lineMenu {
        display: block;
        height: 1px;
        border: 0;
        border-top: 2px solid #073b40e6;
        margin: 1em 0;
        padding: 2px;
    }

    .topMenuNavigation {
        margin-left: 150px;
        padding: 5px;
    }


    .cont {
        display: flex;
        flex-direction: row;
    }

    #zcilkaTopMenuNavigation {
        padding-top: 10px;
        padding-bottom: 10px;
        display: block;
        color: darkblue;
        padding-left: 100px;
        font-size: 20px;
    }



    img {
        width: 15%;
    }

    &:hover {
        background-color: rgba(115,220, 224, 1);
    }
</style>