Search_Work/Models/ArreaDatabase/Contact.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Search_Work.Models.ArreaDatabase
{
    public class Contact
    {
        public Guid Id { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }

    public string Name { get; set; }
    public string Surname { get; set; }

    public string Avatar { get; set; }

    public string Site { get; set; }

        public string Facebook { get; set; }

        public bool Status { get; set; }

        public Employer Employer { get; set; }
        public Guid EmployerId { get; set; }
    }
}

Search_Work/Models/ViewModel/Home/Company/CompanyByFieldActivityViewModel.cs
using Search_Work.Models.Pagination;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Search_Work.Models.ViewModel.Home.Company
{

  public class CompaniesPageByFieldActivityViewModel
  {
    public string FialdActivityName { get; set; }
    public int ActivityInCategoryCount { get; set; }
    public bool IsShowOnlyActive { get; set; }

    public List<CompanyByFieldActivityViewModel> CompaniesByFieldActivity { get; set; }

    public CataloguePaginationViewModel Pagination { get; set; }
  }

  public class CompanyByFieldActivityViewModel
    {
    public Guid СompanyId { get; set; }
    public string CompanyName { get; set; }
    public string CompanyLogoUrl { get; set; }
    public int VacancyCount { get; set; }
  }
}

Search_Work/Models/ViewModel/Home/Company/FieldActivityWhithByCompanyViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Search_Work.Models.ViewModel.Home.Company
{
    public class FieldActivityWhithByCompanyViewModel
    {
    public Guid FieldActivityId { get; set; }
    public string FieldActivityName { get; set; }
  }

  
    public class PageCompaniesByFeldViewModel
  {
    public List<FieldActivityWhithByCompanyViewModel> CompaniesByFeld { get; set; }
  }
}

Search_Work/Controllers/InsertToDBController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Search_Work.Data;
using Search_Work.Models;
using Search_Work.Models.ArreaDatabase;
using Search_Work.Models.ArreaDatabase.Resumes;
using Search_Work.Models.ArreaDatabase.Vacancies;
using Search_Work.Models.DefaultData;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Search_Work.Controllers
{
  public class InsertToDBController : Controller
  {
    private readonly oxana1404 db;
    private readonly UserManager<ApplicationUser> userManager;

    // private IHostingEnvironment _environment;

    public InsertToDBController(oxana1404 _db, UserManager<ApplicationUser> userManager)
    {
      db = _db;
      this.userManager = userManager;
    }
    public ActionResult Insert()
    {

      var count = userManager.Users.Count();


      if (count <= 20)
      {

        ApplicationUser employer = //userManager.Users.FirstOrDefault(u => u.Email == "employer@dominator.ua");
           new ApplicationUser() { Email = "employer@sw.ua", UserName = "employer@sw.ua" };
        ApplicationUser employer1 = //userManager.Users.FirstOrDefault(u => u.Email == "employe1@dominator.ua");
        new ApplicationUser() { Email = "employe1@swr.ua", UserName = "employer1@sw.ua" };
        ApplicationUser employer2 = //userManager.Users.FirstOrDefault(u => u.Email == "employer2@dominator.ua");
        new ApplicationUser() { Email = "employer2@sw.ua", UserName = "employer2@sw.ua" };




        var emplRes = this.userManager.CreateAsync(employer, "Q123_q").Result;
        if (emplRes.Succeeded)
        {
          var roleEmplRes = this.userManager.AddToRoleAsync(employer, "Employer").Result.Succeeded;
        }

        var empl1Res = this.userManager.CreateAsync(employer1, "Q123_q").Result;
        if (empl1Res.Succeeded)
        {
          var roleEmpl1Res = this.userManager.AddToRoleAsync(employer1, "Employer").Result.Succeeded;
        }

        var empl2Res = this.userManager.CreateAsync(employer2, "Q123_q").Result;
        if (empl2Res.Succeeded)
        {
          var roleEmpl2Res = this.userManager.AddToRoleAsync(employer2, "Employer").Result.Succeeded;

        }

       // -------------Activity Fiald------------
        List<FieldActivity> defaultActivitiesList = new List<FieldActivity>()
        {
          new FieldActivity()
          {
            Name = "IT, компьютеры, интернет",
          },
          new FieldActivity()
          {
            Name = "Культура, музыка, шоу-бизнес",
          },
          new FieldActivity()
          {
            Name = "Финансы, банк",
          },
          new FieldActivity()
          {
            Name = "Администрация, руководство среднего звена",
          },
          new FieldActivity()
          {
            Name = "Бухгалтерия, аудит",
          },
          new FieldActivity()
          {
            Name = "Гостинично-ресторанный бизнес, туризм",
          },
          new FieldActivity()
          {
            Name = "Дизайн, творчество",
          },
          new FieldActivity()
          {
            Name = "Красота, фитнес, спорт",
          },
          new FieldActivity()
          {
            Name = "Культура, музыка, шоу-бизнес",
          },
          new FieldActivity()
          {
            Name = "Логистика, склад, ВЭД",
          },
          new FieldActivity()
          {
            Name = "Маркетинг, реклама, PR",
          },
          new FieldActivity()
          {
            Name = "Медицина, фармацевтика",
          },
          new FieldActivity()
          {
            Name = "Недвижимость",
          },
          new FieldActivity()
          {
            Name = "Образование, наука",
          },
          new FieldActivity()
          {
            Name = "Охрана, безопасность",
          },
          new FieldActivity()
          {
            Name = "Продажи, закупки",
          },
          new FieldActivity()
          {
            Name = "Рабочие специальности, производство",
          },
          new FieldActivity()
          {
            Name = "Розничная торговля",
          },
          new FieldActivity()
          {
            Name = "Секретариат, делопроизводство, АХО",
          },
          new FieldActivity()
          {
            Name = "Сельское хозяйство, агробизнес",
          },
          new FieldActivity()
          {
            Name = "СМИ, издательство, полиграфия",
          },
          new FieldActivity()
          {
            Name = "Строительство, архитектура",
          },
          new FieldActivity()
          {
            Name = "Сфера обслуживания",
          },
          new FieldActivity()
          {
            Name = "Телекоммуникации и связь",
          },
          new FieldActivity()
          {
            Name = "Топ-менеджмент, руководство высшего звена",
          },
          new FieldActivity()
          {
            Name = "Транспорт, автобизнес",
          },
          new FieldActivity()
          {
            Name = "Управление персоналом, HR",
          },
          new FieldActivity()
          {
            Name = "Финансы, банк",
          },
          new FieldActivity()
          {
            Name = "Юриспруденция",
          },
          new FieldActivity()
          {
            Name = "Другие сферы деятельности",
          },
        };

        defaultActivitiesList.ForEach(fieldActivity => fieldActivity.Id = Guid.NewGuid());


        foreach (var activity in defaultActivitiesList)
        {
          db.FieldActivities.Add(activity);
        }
        db.SaveChanges();
        defaultActivitiesList = db.FieldActivities.ToList();
        // -----------------------------------------------------------

        Employer defaultEmployer1 = new Employer();
        defaultEmployer1.Id = Guid.NewGuid();

        Employer defaultEmployer2 = new Employer();
        defaultEmployer2.Id = Guid.NewGuid();

        Employer defaultEmployer3 = new Employer();
        defaultEmployer3.Id = Guid.NewGuid();

        // --------------- Default City -------------------
        var defaultCity1 = new City()
        {
          Id = Guid.NewGuid(),
          Name = "Київ"
        };


        var defaultCity2 = new City()
        {
          Id = Guid.NewGuid(),
          Name = "Дніпро"
        };


        var defaultCity3 = new City()
        {
          Id = Guid.NewGuid(),
          Name = "Харків"
        };


        //cityRepo.Add(defaultCity1);
        //cityRepo.Add(defaultCity2);
        //cityRepo.Add(defaultCity3);
        // db.Cities.SaveCh();

        // --------------- Default Company -------------------
        var defaultCompany1 = new Company()
        {
          Id = Guid.NewGuid(),
          Name = "AutoEs",
          Description = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque " +
                          "laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto " +
                          "beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut " +
                          "odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. "// +
                                                                                                                           //"Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, " +
                                                                                                                           //"sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat " +
                                                                                                                           //"voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit " +
                                                                                                                           //"laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit " +
                                                                                                                           //"qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum " +
                                                                                                                           //"fugiat quo voluptas nulla pariatur?"
        };

        var defaultCompany2 = new Company()
        {
          Id = Guid.NewGuid(),
          Name = "Vodafone",
          Description = "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis " +
                          "praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias " +
                          "excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui " +
                          "officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum " +
                          "facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi " +
                          "optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas "// +
                                                                                                                        //"assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut " +
                                                                                                                        //"rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. " +

Search_Work/Controllers/RolesController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Search_Work.Data;
using Search_Work.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Search_Work.Controllers
{
    public class RolesController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        UserManager<ApplicationUser> _userManager;
        private readonly oxana1404 _context;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager, oxana1404 context)
        {
            _roleManager = roleManager;
            _userManager = userManager;

            _context = context;
        }
        public IActionResult Index()
        {
            return View(_roleManager.Roles.ToList());
        }


        public IActionResult Create() => View();
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());

	   //public async Task<IActionResult> UserList()
	   //{

	   //    var users = _userManager.Users;
	   //    var roles = new List<string>();
	   //    foreach (var user in users.ToList())
	   //    {
	   //        string str = "";
	   //        foreach (var role in _userManager.GetRolesAsync(user))
	   //        {
	   //            str = (str == "") ? role.ToString() : str + " - " + role.ToString();
	   //        }
	   //        roles.Add(str);
	   //    }
	   //    var model = new ListUserViewModel()
	   //    {
	   //        users = users.ToList(),
	   //        roles = roles.ToList()
    //       }
           //var users = _userManager.Users.ToList();
           //  var rolesForUser = await _userManager.GetRolesAsync(userId);

                //       var model = new UsersViewModel
                //{
                // Users = users.Select(u => new List<UserViewModel>()
                // {
                //              new UserViewModel()
                //              {
                //    //  Id = u.Id,
                //      UserName = u.Email,
                //      Roles = _userManager.GetRolesAsync(u.Id).ToString()
                //   }
                // }),
                //};
    //        return View(model);
	   //}

        public async Task<IActionResult> Edit(string userId)
        {
            // получаем пользователя
            var user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            // получаем пользователя
            var user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                // получаем все роли
                var allRoles = _roleManager.Roles.ToList();
                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteUser(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
               

                  var cand = _context.Candidates.FirstOrDefault(i => i.AccountUser == user);
                  var emp = _context.Employers.FirstOrDefault(i => i.AccountUser == user);

                  if (cand != null)
                    _context.Candidates.Remove(cand);    
                  else if (emp != null)
                    _context.Employers.Remove(emp);

                var result = await _userManager.DeleteAsync(user);
            }
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(UserList));
        }
    }
}

Search_Work/Views/Home/About.cshtml
@model Search_Work.Models.ProfileViewModel
@{
    ViewData["Title"] = "About";
}

@{
  string userRole = "";
  if (User.Identity.IsAuthenticated)
  {


      if (User.IsInRole("Admin"))
      {
          userRole = "Admin";
      }
      else if (User.IsInRole("Employer"))
      {
          userRole = "Employer";
      }
      else if (User.IsInRole("Candidate"))
      {
          userRole = "Candidate";
      }

      var r = userRole;
  }
}


<hr />
<div id="container">
    <h3> Кабінет </h3>
</div>
<hr />

<div id="container">

    <div id="menu">
        @{
            var i = ViewBag.Employee;
        }
        @if (User.Identity.Name == "admin@gmail.ua")
        {
            <hr />
            <ul id="menu">
                <li><a id="linc" asp-action="UserList" asp-controller="Roles">Кабінет Admin </a></li>
            </ul>
            <hr />
            <ul id="menu">
                <li><a id="linc" asp-area="" asp-controller="Cities" asp-action="Index">Міста</a></li>
                <li><a id="linc" asp-area="" asp-controller="Companies" asp-action="Index">Компанії</a></li>
                <li><a id="linc" asp-action="UserList" asp-controller="Roles">Користувачі </a></li>
            </ul>
            @*<li><a id="linc" asp-action="Index" asp-controller="Goods"> Товари</a></li>
            <li><a id="linc" asp-controller="Emploees" asp-action="Index">Працівники</a></li>


            <li><a id="linc" asp-action="Index" asp-controller="Providers">Постачальники </a></li>*@

        }
        else if (Model.Employer != null)
        {
            if (Model.Company == null)
            {
                <hr />
                <ul id="menu">
                    <li> <a id="linc" asp-controller="Employers" asp-action="PageIsExistCompany" asp-route-id="@Model.Employer.Id">Створити профіль</a></li>
                </ul>
            }
            else
            {
                <hr />
                <ul id="menu">

                    @*<li> <a id="linc" href="@Url.Action( "Details", "Companies" ,new { id = Model.Company.Id,  empId = Model.Employer.Id })">Профіль</a></li>*@
                    <li> <a id="linc" href="@Url.Action( "EditEmployee", "Employee", new{ employerId = Model.Employer.Id  })">Профіль</a></li>
                    <li> <a id="linc" href="@Url.Action( "ProfileCompany", "Company", new{   })">Компанія</a></li>
                    <li> <a id="linc" href="@Url.Action( "EmploeeVacancies", "Vacancy", new{  })">Вакансії</a></li>
                    <li> <a id="linc" href="@Url.Action( "SavedResume", "Company", new{   })">Збережені резюме</a></li>
                </ul>
            }


        }
        else if (Model.Candidate != null)
        {

            <hr />
            <ul id="menu">
                <li> <a id="linc" asp-controller="Candidates" asp-action="Details" asp-route-id="@Model.Candidate.Id">Профіль</a></li>
                <li> <a id="linc" href="@Url.Action( "Index", "Resume", new{ candidateId = @Model.Candidate.Id  })">Pезюме</a></li>

              
            </ul>
            <hr />
            <ul id="menu">
               
                <li> <a id="linc" asp-controller="Vacancy" asp-action="RecommendedVacancy" asp-route-id="">Рекомендовані вакансії</a></li>
            </ul>



        }


    </div>

    <hr />
    <ul id="menu">
        @*<li><a id="linc" asp-controller="BuyOrders" asp-action="Index">Купівля товару</a></li>

            <li><a id="linc" asp-action="Index" asp-controller="SaleOrders">Продаж товару </a></li>
            <li><a id="linc" asp-action="Index" asp-controller="Stoks">Склад </a></li>*@

    </ul>

</div>
<hr />



<style>
    #menu, #menu li {
        margin: 0;
        padding: 0;
    }

    #menu {
        text-align: center;
    }

        #menu li {
            display: inline-block;
            text-align: center;
            width: 15%; /* задаем размер пункта можно в пикселях*/
        }

        #menu a {
            display: block;
            padding: 15px;
            color: #fff;
            font-size: 100%;
            text-decoration: none;
            background: #03658e;
            margin-right: 5px; /* добавляем отступы между пунктами */
        }

            #menu a:hover {
                background: #00ffff;
            }

    #container {
        background-color: aliceblue;
        border: 1px solid #ddd;
        border-radius: 4px;
        padding: 25px;
    }
</style>

Search_Work/Views/Home/Contact.cshtml
@*@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>*@

@{
  ViewData["Title"] = "Контакти"; ;
}
<h2>@ViewData["Title"]</h2>
@*<h3>@ViewData["Message"]</h3>*@

<hr />
<div id="bacground">
    <p>
        <img src="~/images/Tel.jpg" />
        &nbsp; Tel : +3809876542
    </p>


    <p>
        <img src="~/images/email.jpg" />

        &nbsp; Email : "admin@23gmai.ua"
    </p>
</div>
<hr />
<p>
    <a href="https://www.google.com.ua/search?ei=JckTW7-NEoGjsgHg4LaQDA&q=%D0%B3%D0%BC%D0%B8%D1%80%D1%96+1&oq=%D0%B3%D0%BC%D0%B8%D1%80%D1%96+1&gs_l=psy-ab.3...1473.3243.0.4049.0.0.0.0.0.0.0.0..0.0....0...1.1.64.psy-ab..0.0.0....0.XHOft2eBvWM">
        <img id="imgAddress" src="~/images/Karta.png" alt="lorem">
    </a>
    &nbsp; Adressa: Київ, вул. Гмирі, 1
</p>

<style>
    #bacground {
        background-color: aliceblue;
    }

    img {
        border: 1px solid #ddd;
        border-radius: 4px;
        padding: 5px;
        width: 80px;
        height: 80px;
    }

    p {
        font-weight: bold;
        font-size: 20px;
        padding: 10px;
    }

    #imgAddress {
        width: 180px;
        height: 130px;
    }
</style>

Search_Work/Views/Home/Index.cshtml
@model Search_Work.Models.ViewModel.Home.HomePageViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="topMenu">
    <div class="contMenu">



        @if (ViewBag.UsersCount < 20)
        {
            <h3> <a id="linc" asp-action="Insert" asp-controller="InsertToDB"><b>Заповнити ДБ !!!</b></a></h3>

        }


    </div>
</div>

<hr id="lineMenu" />
<form>
    <hr />
    <div>





    </div>
    <hr />
    <div>
        <h2> <b>Search_Work - САЙТ З ПОШУКУ РОБОТИ !</b></h2>
    </div>

    <hr />
    <div class="row" id="container">



        <div class="heading">
            <h2 class="center">Вакансії від провідних компаній</h2>

        </div>
        <hr />
        <div class="logoList">

            @foreach (var company in Model.VacanciesFromTopCompanies)
            {
                <a href="@Url.Action("AboutCompany", "CompanyHome", new {companyId = company.CompanyId})">

                    @{
                        if (company.CompanyLogoUrl == null)
                        {
                            <img id="logo" src="~/images/LogoCompany.png" title="@company.CompanyName" />
                        }
                        else
                        {
                            <img id="logo" src="@company.CompanyLogoUrl" title="@company.CompanyName" />

                        }
                    }
                </a>
            }
        </div>
    </div>

    <hr />
    <div class="row" id="container">
        <h3> <b>Нові вакансії</b></h3>
        <hr />
        <div class="row" id="container">

            @foreach (var i in Model.NewVacancies)
            {

                <div id="menu">
                    <div id="a">
                        <span><a href="@Url.Action("AboutVacancy", "Vacancy", new { vacancyId = i.VacancyId })">@i.VacancyName</a></span>
                        <span> - @i.Salary</span>
                        <span>&nbsp;грн</span>
                        <p>
                            @i.CompanyName , @i.CityName
                        </p>
                    </div>
                </div>

            }


        </div>
    </div>

    <hr />





    <div class="row" id="container">
        <h3> <b>Вакансії по сферах діяльності</b></h3>
        </hr>
        <div class="row" id="container" style="float: left; width: 49%; margin-left: 10px;">
            @for (var i = 0; i < Model.VacanciesByFieldActivity.Count() / 2; i++)
            {
                <div>
                    <div id="a">
                        <a href="@Url.Action("VacancyCatalogByActivityField", "Vacancy",
                        new { fieldActivityId =  Model.VacanciesByFieldActivity[i].FieldId })">@Model.VacanciesByFieldActivity[i].FieldName</a>
                    </div>
                </div>
            }

        </div>
        <div class="row" id="container" style="float: left; width: 49%; margin-left: 20px;">
            @for (var i = Model.VacanciesByFieldActivity.Count() / 2; i < Model.VacanciesByFieldActivity.Count(); i++)
            {
                <div>
                    <div id="a">
                        <a href="@Url.Action("VacancyCatalogByActivityField", "Vacancy", new { fieldActivityId = Model.VacanciesByFieldActivity[i].FieldId })">@Model.VacanciesByFieldActivity[i].FieldName</a>

                    </div>
                </div>
            }

        </div>
    </div>

    @*@foreach (var field in Model.VacanciesByFieldActivity)
        {

            <div>
                <div>
                    <a href="@Url.Action("VacancyCatalogByActivityField", "Vacancy", new { fieldActivityId = field.FieldId })">@field.FieldName</a>
                </div>
            </div>

        }*@



    <hr />
    <div class="row" id="container">



        <h3 class="left primaryColor"><b>Вакансії по містам</b></h3>
        <hr />

        <div class="row" id="container" style="float: left; width: 49%; margin-left: 10px;">
            @for (var i = 0; i < Model.VacanciesByCity.Count() / 2; i++)
            {
                <div>
                    <div id="a">
                        <a href="@Url.Action("VacancyCatalogByCityld", "Vacancy", new { cityId = Model.VacanciesByCity[i].CityId })">@Model.VacanciesByCity[i].CityName</a>
                    </div>
                </div>
            }

        </div>
        <div class="row" id="container" style="float: left; width: 49%; margin-left: 20px;">
            @for (var i = Model.VacanciesByCity.Count() / 2; i < Model.VacanciesByCity.Count(); i++)
            {
                <div>
                    <div id="a">
                        <a href="@Url.Action("VacancyCatalogByCityld", "Vacancy", new { cityId = Model.VacanciesByCity[i].CityId })">@Model.VacanciesByCity[i].CityName</a>

                    </div>
                </div>
            }

        </div>
    </div>


    @*@foreach (var city in Model.VacanciesByCity)
    {
        <p>
            <a href="@Url.Action("VacancyCatalogByCityld", "Vacancy", new { cityId = city.CityId })">@city.CityName</a>
        </p>
    }

    </div>*@



</form>


<style>

    #menu {
        margin: 0;
        padding: 0;
    }

    #menu {
        text-align: center;
    }

    #menu {
        display: inline-block;
        text-align: center;
        width: 20%; /* задаем размер пункта можно в пикселях*/
    }

    #menu, #a {
        padding: 3px;
        font-size: 100%;
        margin-right: 10px; /* добавляем отступы между пунктами */
    }




    #cont {
        border: 1px solid #ddd;
        border-radius: 4px;
        padding: 20px;
    }

    img {
        width: 60%;
    }

    #logo {
        width: 70px;
        padding: 5px;
    }

    h2 {
        text-align: center;
        color: darkblue;
        font-family: 'Times New Roman', Times, serif;
    }

    .masterForm {
        background-color: antiquewhite;
    }

    #zcilkaTopMenuNavigation {
        padding-top: 10px;
        padding-bottom: 10px;
        display: block;
        color: darkblue;
        padding-left: 100px;
        font-size: 20px;
    }


    &:hover {
        background-color: rgba(115,220, 224, 1);
    }
</style>
<style>
    #lineMenu {
        display: block;
        height: 1px;
        border: 0;
        border-top: 2px solid #073b40e6;
        margin: 1em 0;
        padding: 2px;
    }

    .topMenu {
        margin-left: 150px;
        padding: 5px;
    }



    .contMenu {
        display: flex;
        flex-direction: row;
    }

    #zcilkaTopMenu {
        padding-top: 10px;
        padding-bottom: 10px;
        display: block;
        color: darkblue;
        padding-left: 100px;
        font-size: 20px;
    }

    img {
        width: 5%;
    }

    &:hover {
        background-color: rgba(115,220, 224, 1);
    }
</style>

Search_Work/Views/Home/VacanciesHomePage.cshtml
@model Search_Work.Models.ViewModel.Home.HomePageViewModel