Search_Work/Arrea/Candidate/Controllers/EditResumeController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Search_Work.Arrea.Candidate.Models.Resume;
using Search_Work.Data;
using Search_Work.Models;
using Search_Work.Models.ArreaDatabase.Resumes;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Search_Work.Arrea.Candidate.Controllers
{
    public class EditResumeController : Controller
    {
        private readonly oxana1404 db;

        private IHostingEnvironment _environment;

        public EditResumeController(oxana1404 db, IHostingEnvironment environment)
        {
            this.db = db;
            //this._userManager = userManager;
            _environment = environment;
        }

        // Сфера діяльності
        public ActionResult AddFieldActivitiy(Guid resumeId)
        {
            var resume = db.Resumes.Include(r => r.Candidate).ThenInclude(r => r.AccountUser)
                        .Include(r => r.FieldActivities)
                       .FirstOrDefault(i => i.Id == resumeId);

            var model = new AddResumeFieldActivitiesViewModel()
            {
                Resume = resume,

            };

            model.FieldActivities = db.FieldActivities.Include(f => f.Resumes)
                                                        .Select(e => new SelectListItem()
                                                        {
                                                            Value = e.Id.ToString(),
                                                            Text = e.Name
                                                        }).ToList();


            return View("/Arrea/Candidate/Views/Resumes/EditResume/AddFieldActivities.cshtml", model);

        }

        [HttpPost]
        public ActionResult AddFieldActivitiy(AddResumeFieldActivitiesViewModel model)
        {
            var resume = db.Resumes.Include(r => r.Candidate).ThenInclude(r => r.AccountUser)
                        .Include(r => r.FieldActivities).ThenInclude(r => r.FieldActivity)
                       .FirstOrDefault(i => i.Id == model.ResumeId);

            var fieldActivity = db.FieldActivities.FirstOrDefault(e => e.Id == model.FieldActivityId);

            var newFieldActivity = new FieldActivityResume()
            {
                Id = Guid.NewGuid(),
                Resume = resume,
                FieldActivity = fieldActivity,
                
            };
            resume.DateChange = DateTime.Now;
            // newExp.EmploymentId = employment.Id;


            resume.FieldActivities.Add(newFieldActivity);
            db.Update(resume);
            db.SaveChanges();

            return RedirectToAction("Edit", "Resume", new { resumeId = model.ResumeId });
        }

        // Досвід роботи 
        public ActionResult AddExperiences(Guid resumeId)
        {
            var resume = db.Resumes.Include(r => r.Candidate).ThenInclude(r => r.AccountUser)
                        .Include(r => r.Experiences).ThenInclude(r => r.Employment)
                       .FirstOrDefault(i => i.Id == resumeId);



            var model = new AddResumeExpiriensViewModel()
            {
                Resume = resume,

            };
            model.Employments = db.Employments.Include(e => e.Experiences)
                                                        .ThenInclude(f => f.Resume).Select(e => new SelectListItem()
                                                        {
                                                            Value = e.Id.ToString(),
                                                            Text = e.Name
                                                        }).ToList();

            return View("/Arrea/Candidate/Views/Resumes/EditResume/AddExperiences.cshtml", model);
        }

        [HttpPost]
        public ActionResult AddExperiences(AddResumeExpiriensViewModel model)
        {
            var resume = db.Resumes.Include(r => r.Candidate).ThenInclude(r => r.AccountUser)
                        .Include(r => r.Experiences).ThenInclude(r => r.Employment)
                       .FirstOrDefault(i => i.Id == model.ResumeId);

            var employment = db.Employments.FirstOrDefault(e => e.Id == model.EmploymentId);

            var newExp = new Experience()
            {
                Id = Guid.NewGuid(),
                Resume = resume,
                DateWorkFrom = model.DateWorkFrom,
                DateWorkTo = model.DateWorkTo,
                IsWorkingNow = model.IsWorkingNow,

                Employment = employment,
                Position = model.Position,
                Task = model.Task,
                Progres = model.Progres

            };

            resume.DateChange = DateTime.Now;


            resume.Experiences.Add(newExp);
            db.Update(resume);
            db.SaveChanges();

            return RedirectToAction("Edit", "Resume", new { resumeId = model.ResumeId });
        }
        // Реализованные проекты
        public ActionResult AddImplementedProjects(Guid resumeId)
        {
            var resume = db.Resumes.Include(r => r.Candidate).ThenInclude(r => r.AccountUser)
                        .Include(r => r.ImplementedProjects)
                       .FirstOrDefault(i => i.Id == resumeId);

            var model = new AddResumeImplementsProgectViewModel()
            {
                Resume = resume,
            };

            return View("/Arrea/Candidate/Views/Resumes/EditResume/AddImplementedProjects.cshtml", model);

        }

        [HttpPost]
        public ActionResult AddImplementedProjects(AddResumeImplementsProgectViewModel model)
        {

            var resume = db.Resumes.Include(r => r.Candidate).ThenInclude(r => r.AccountUser)
                   .Include(r => r.ImplementedProjects)
                  .FirstOrDefault(i => i.Id == model.ResumeId);

            var impProgect = db.ImplementedProjects.Include(e => e.Resume).FirstOrDefault(e => e.Id == model.Id);

            var newImplementProgect = new ImplementedProject()
            {
                Id = Guid.NewGuid(),
                NameProgect = model.NameProgect,
                DateWorkFrom = model.DateWorkFrom,
                DateWorkTo = model.DateWorkTo,
                LinkToProgect = model.LinkToProgect,

                Resume = resume,

            };

            resume.DateChange = DateTime.Now;
            resume.ImplementedProjects.Add(newImplementProgect);
            db.Update(resume);
            db.SaveChanges();

            return RedirectToAction("Edit", "Resume", new { resumeId = resume.Id });
        }

        // Образование
        public ActionResult AddEducation(Guid resumeId)
        {
            var resume = db.Resumes.Include(r => r.Candidate).ThenInclude(r => r.AccountUser)
                        .Include(r => r.Educations).ThenInclude(e => e.LevelEducation)
                        .Include(r => r.Educations).ThenInclude(e => e.FormTraining)
                       .FirstOrDefault(i => i.Id == resumeId);



            var model = new AddResumeEducationViewModel()
            {
                Resume = resume
            };
            model.LevelEducations = db.LevelEducations.Include(f => f.Educations)
                                                           .ThenInclude(f => f.Resume).Select(level => new SelectListItem()
                                                           {
                                                               Value = level.Id.ToString(),
                                                               Text = level.Name
                                                           }).ToList();
            model.FormTrainings = db.FormTrainings.Include(f => f.Educations)
                                                   .ThenInclude(f => f.Resume).Select(form => new SelectListItem()
                                                   {
                                                       Text = form.Name,
                                                       Value = form.Id.ToString()
                                                   }).ToList();

            return View("/Arrea/Candidate/Views/Resumes/EditResume/AddEducation.cshtml", model);

        }

        [HttpPost]
        public ActionResult AddEducation(AddResumeEducationViewModel model)
        {

            var resume = db.Resumes.Include(r => r.Candidate).ThenInclude(r => r.AccountUser)
                         .Include(r => r.Educations).ThenInclude(e => e.LevelEducation)
                         .Include(r => r.Educations).ThenInclude(e => e.FormTraining)
                        .FirstOrDefault(i => i.Id == model.ResumeId);

            var formTr = db.FormTrainings.Include(e => e.Educations).FirstOrDefault(e => e.Id == model.FormTrainingId);
            var lev = db.LevelEducations.Include(e => e.Educations).FirstOrDefault(e => e.Id == model.LevelEducationId);

            var newEducation = new Education()
            {
                Id = Guid.NewGuid(),

                LevelEducation = lev,
                NameInstitution = model.NameInstitution,
                City = model.City,
                DateWorkFrom = model.DateWorkFrom,
                DateWorkTo = model.DateWorkTo,
                FormTraining = formTr,

                Resume = resume,

            };
            resume.DateChange = DateTime.Now;

            resume.Educations.Add(newEducation);
            db.Update(resume);
            db.SaveChanges();

            return RedirectToAction("Edit", "Resume", new { resumeId = resume.Id });
        }

        // Знание іноземних мов
        public ActionResult AddForeignLanguage(Guid resumeId)
        {
            var resume = db.Resumes.Include(r => r.Candidate).ThenInclude(r => r.AccountUser)
                        .Include(r => r.ForeignLanguages)

Search_Work/Arrea/Candidate/Controllers/ResumeCreateController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Search_Work.Arrea.Candidate.Models.Resume;
using Search_Work.Controllers.Arrea.Candidate.Controllers;
using Search_Work.Data;
using Search_Work.Models;
using Search_Work.Models.ArreaDatabase.Resumes;
using Search_Work.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Search_Work.Arrea.Candidate.Controllers
{
    public class ResumeCreateController : Controller
    {
        private readonly oxana1404 db;
        private readonly UserManager<ApplicationUser> _userManager;
        private IHostingEnvironment _environment;

        public ResumeCreateController(oxana1404 db, UserManager<ApplicationUser> userManager, IHostingEnvironment environment)
        {
            this.db = db;
            this._userManager = userManager;
            _environment = environment;
        }




        public ActionResult AddResume()
        {
            // IDENTITY USER NAME  HttpContext
            var userName = HttpContext.User.Identity.Name;

            var candidate = db.Candidates.Include(c => c.AccountUser)
              .FirstOrDefault(x => x.AccountUser.UserName == userName);

            var fieldsActivity = db.FieldActivities.Select(field => new FieldActivityViewModel()
            {
                Name = field.Name,
                Id = field.Id
            }).ToList();

            var model = new Models.Resume.AddResumeViewModel()
            {
                CandidateId = candidate.Id,
                FieldsActivity = fieldsActivity
            };

            return View("/Arrea/Candidate/Views/Resumes/AddResume.cshtml", model);
        }

        [HttpPost]
        public async Task<ActionResult> AddResume(AddResumeViewModel model, IFormFile Image)
        {
            var candidate = db.Candidates.Include(c => c.AccountUser)
              .FirstOrDefault(x => x.Id == model.CandidateId);

            var newResume = new Resume()
            {
                Id = Guid.NewGuid(),
                Name = model.Name,
                // FieldActivities.
            };
            FieldActivityResume fieldActResume = null;

            var fieldActivity = db.FieldActivities.FirstOrDefault(f => f.Id == model.FieldId);
            if (fieldActivity != null)
            {
                fieldActResume = new FieldActivityResume()
                {
                    Resume = newResume,
                    Id = Guid.NewGuid(),
                    FieldActivity = fieldActivity,
                };
            }

            newResume.Candidate = candidate;

            if (Image != null)
            {
                string name = Image.FileName;
                string path = $"/files/{name}";
                string serverPath = $"{_environment.WebRootPath}{path}";
                FileStream fs = new FileStream(serverPath, FileMode.Create,
                    FileAccess.Write);
                await Image.CopyToAsync(fs);
                fs.Close();
                newResume.Foto = path;
            }


            newResume.Salary = model.Salary;

            // Todo AnonimResume  IsAnonymousResume

            newResume.Candidate.LastName = model.LastName;
            newResume.Candidate.Name = model.Name;

            newResume.Candidate.Surname = model.Surname;
            newResume.Candidate.Sex = model.Sex;
            newResume.Candidate.Birthday = model.Birthday;
            // Todo Phones ????
            newResume.Candidate.PhoneNumber = model.Phone;
            newResume.Candidate.Email = model.Email;
            newResume.Candidate.Facebook = model.Fasebook;
            newResume.Candidate.Linkedin = model.Linkedin;
            newResume.Candidate.Skype = model.Skype;

            newResume.DateCreate = DateTime.Now;
            newResume.DateChange = DateTime.Now;


            newResume.Candidate.Country = model.Country;
            newResume.Candidate.Region = model.Region;
            // newResume.Candidate.City = city;
            newResume.Candidate.Street = model.Street;
            newResume.Candidate.ApartmentNumber = model.ApartmentNumber;

            db.Resumes.Add(newResume);
            db.SaveChanges();

            return RedirectToAction(nameof(ResumeController.Edit), "Resume", new { resumeId = newResume.Id });

            // return Redirect("Edit", "Resume", new { resumeId  == newResume.Id});
        }
    }
}

Search_Work/Arrea/Candidate/Views/Index.cshtml
@using Search_Work.Models.Helper
@*@using Search_Work.Models.ActionForCandidat*@
@model Search_Work.Arrea.Candidate.Models.CandidateResumesViewModel

@{

  Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="topMenuNavigation">
    <div class="cont">

        <a id="zcilkaTopMenuNavigation" href="@Url.Action("PaternSearchVacancy", "Vacancy")"><b> Шаблони пошуку</b></a>
        <a id="zcilkaTopMenuNavigation" href="@Url.Action("ResponsesToResume", "Vacancy")"><b> Відгуки</b></a>
        <a id="zcilkaTopMenuNavigation" href="@Url.Action("SavedVacancy", "Vacancy")"><b> Збережені вакансії</b></a>
    </div>
</div>


<hr id="lineMenu" />
<div class="row" id="container">
    <span style="float: left; width: 49%">
        <h3><b>Мої резюме </b></h3>
    </span>
    <span style="float: left; width: 49%">
        
        <button type="button" onclick="location.href='@Url.Action("AddResume", "ResumeCreate" , new {})'"> Нове резюме </button>
        @*<button type="button" onclick="location.href='@Url.Action("Create", "Resume" , new {})'"> Нове резюме </button>*@
    </span>

</div>
<hr />
<div class="row" id="container">
 
    <table class="table">
        <thead>
            <tr>
                <th>
                    <h4><b>Назва </b></h4>
                </th>
                <th>
                    <h4><b>Дата змін</b></h4>
                </th>
               
                <th>
                    <h4><b>Показів</b></h4>
                </th>
                <th>
                    <h4><b>Переглядів</b></h4>
                </th>
                <th>
                    <h4><b>Статус</b></h4>
                </th>
                <th>
                   
                </th>

            </tr>
        </thead>
        <tbody>
            @foreach (var res in Model.Resumes)
            {
            <tr>
                <td>
                    <a  href="@Url.Action( @*"EditResume"*@ "Edit", "Resume", new { resumeId = res.Id })">
                        <b>@res.NameResum</b>
                    </a>
                    <p>@res.Wage грн, @res.City</p>
                </td>
                <td>

                    @if (res.DateChange == DateTime.MinValue)
                    {
                        <p> - </p>
                    }
                    else
                    {
                        <p> @res.DateChange.ToString("dd/MM/yyyy")</p>
                    }
                    
                </td>
               <td>
                    @res.CountShow
                </td>
                <td>
                    <a href="@Url.Action("ViewsResume", "Resume", new { resumeId = res.Id })"> <span>(@res.CountView )  </span></a>
                </td>
                <td>
                    @if(res.Status == true)
                    {
                      <h4 id="Activ"><b>Активне</b></h4>
                    }
                    else
                    {

                    <h4 id="Activ"><b>Не активне</b></h4>
                    }
                </td>
                <td>
                    <a href="@Url.Action( "Edit", "Resume", new { resumeId = res.Id })"> Редагувати
                    </a>
                    <hr />
                    <a href="@Url.Action( "DeleteResume", "EditResume", new { resumeId = Model.UserId })">
                        Видалити
                    </a>
                  
                   
                </td>
               
            </tr>
            }
        </tbody>
    </table>
    
</div>

<div class="row" id="container">
    @Html.Partial("~/Views/Shared/Elements/CataloguePagination/_cataloguePagination.cshtml", @Model.Pagination)
</div>

<style>
    #Activ {

        color: blue;
    
    }
    #lineMenu {
        display: block;
        height: 1px;
        border: 0;
        border-top: 2px solid #073b40e6;
        margin: 1em 0;
        padding: 2px;
    }

    th {
        text-align: center;
        padding:20px;
    }
    .topMenuNavigation {
        
    }
    #zcilkaTopMenuNavigation {
        padding-left: 150px;
        font-size: 20px;
    }
    .cont {
        display: flex;
        flex-direction: row;
    }

    a {
        padding-top: 10px;
        padding-bottom: 10px;
        display: block;
        color:darkblue;
        font-size: 16px;
        padding-left: 50px;
        padding-right: 16px;
    }

    &:hover {
        background-color: rgba(115,220, 224, 1);
    }
</style>